name: Bender-action
description: Azure OpenAI GH Action copilot
author: ahelal

inputs:
  mode:
    description: 'Mode of operation (job|pr)'
    required: true
    default: 'job'

  gh-token:
    description:
      GH personal access token (if using private repos or PR mode for
      commenting)
    required: false

  gh-job:
    description:
      Specify the failed job name. If not defined will loop through all job and
      pick first failed one.
    required: false

  az-openai-endpoint:
    description:
      Azure OpenAI Endpoint URL, example
      https://eastus2.api.cognitive.microsoft.com"
    required: true

  az-openai-deployment:
    description: Azure OpenAI deployment name
    required: true

  az-openai-key:
    description: Azure OpenAI API Key
    required: true

  az-openai-apiVersion:
    description: Azure OpenAI version
    default: '2024-05-01-preview'

  dir-context:
    description: Provide the directory structure as base64 extra context
    default: ''

  project-context:
    description:
      Provide the github project metadata as extra context (true|false)
    default: 'false'

  job-context:
    description:
      Should the github action YAML be provided as context (true|false)
    default: 'false'

  user-context:
    description: Extra OpenAI user context
    default: ''

  include:
    description:
      In PR mode, include files to be used, comma seperated regex i.e.
      'src/*.ts' '*.ts;*.js'
    default: ''
    required: false

  annotations:
    description: Use annotations insteead of comments in PR mode
    required: false

outputs:
  usage:
    description: 'OpenAI usage details'

runs:
  using: node20
  main: dist/index.js
